var a = 100; var b = 13; var c = 10; var linebreak = "<br>";
document.write("arithmetic <br>");

document.write("a + b + c = ");

 result = a + b + c;
document.write(result);
document.write(linebreak);

document.write("a + b = ");
 result = a + b;
document.write(result);
document.write(linebreak);

document.write("a - b = "); 
result = a - b;
document.write(result);
document.write(linebreak);

document.write("a / b = ");
 result = a / b;
document.write(result);
document.write(linebreak);

document.write("a % b = ");
 result = a % b;
document.write(result);
document.write(linebreak);

var a = 10;
 var b = 20;
 var linebreak = "<br />"; 

 document.write("comparision <br>");

 document.write("(a == b) => ");
  result = (a == b);
   document.write(result);
 document.write(linebreak);

 document.write("(a < b) => ");
  result = (a < b);
   document.write(result); 
   document.write(linebreak);

   document.write("(a > b) => ");
    result = (a > b);
     document.write(result);
      document.write(linebreak);

      document.write("(a != b) => ");
       result = (a != b);
        document.write(result);
         document.write(linebreak);

         document.write("(a >= b) => ");
          result = (a >= b);
           document.write(result);
            document.write(linebreak);

            document.write("(a <= b) => ");
             result = (a <= b);
              document.write(result);
               document.write(linebreak);




               var a = 40;
                var b = 20; 
                var linebreak = "<br />";
                document.write("assignment <br>");

                 document.write("Value of a => (a = b) => ");
                  result = (a = b);
                   document.write(result);
                   document.write(linebreak);

                    document.write("Value of a => (a += b) => ");
                     result = (a += b);
                      document.write(result);
                      document.write(linebreak);

                       document.write("Value of a => (a -= b) => ");
                       result = (a -= b);
                        document.write(result);
                         document.write(linebreak);

                          document.write("Value of a => (a *= b) => ");
                           result = (a *= b); 
                           document.write(result);
                            document.write(linebreak);

                             document.write("Value of a => (a /= b) => ");
                              result = (a /= b); document.write(result);
                               document.write(linebreak);

                                document.write("Value of a => (a %= b) => ");
                                 result = (a %= b); document.write(result);
                                  document.write(linebreak);







